### ISSUE TITLE
Test with multiprocessing and multi GPU

### ISSUE THREAD

**Issue by pikerbright** [NVIDIA/nvvl#10]
I try to use 4 python multiprocessing to accelerate the decoding. In each processing, I create a nvvl video reader on the same device 0 and decode video. But I found that the decoding speed is a little improved. I wonder if there is any mistake.

Also I try to use multi GPU, 4 device, 4 processing, one on one. Finally I found that the decoding speed is lower than only use one device with one processing.
Experiment need some code revision like:

    def _create_tensor_map(self, batch_size=1):
        tensor_map = {}
        with torch.cuda.device(self.device_id):
            for name, desc in self.processing.items():
                tensor_map[name] = desc.tensor_type(batch_size, *desc.get_dims())
        return tensor_map

Can you help me about this issue?
Thanks very much.

**Comment by jaredcasper** [comment]
In this first case, I wouldn't expect a considerable speed up because each GPU only has a single hardware video decoder, so it will have to be multiplexed between the various streams in this case.

In the second case, thanks for hunting down the problem. :) In our own code we have always set the torch device early on for each process (using `torch.cuda.set_device()`). So the python modules were inadvertently assuming the current torch cuda device was the correct device for the loader. Does your change fix your performance issue?
