### ISSUE TITLE
RTSP

### ISSUE THREAD

**Issue by tugstugi** [NVIDIA/nvvl#104]
Does NVVL support RTSP streams?

**Comment by jaredcasper** [comment]
If FFmpeg (i.e. libavformat) can read and parse it, it should work in theory, but nobody I know of has done it. Might have troubles seeking to random positions within the stream.

Note that its best if you can use DALI instead of this NVVL library directly.  DALI now has video loading support based off of NVVL and is an actual supported product instead of NVVL which is really just example code from a research project and is not supported.
