### ISSUE TITLE
How to set label/target in nvvl.VideoDataset?

### ISSUE THREAD

**Issue by shinkyo0513** [NVIDIA/nvvl#21]
For some tasks like video classification, the iterator of dataset tends to contain both the tensor of videos' frames and the class label. In standard pytorch dataset, we tend to customize __getitem__ and let it reture a dictionary containing video's tensor and its label/target. However, what is the good solution to let nvvl.VideoDataset return video's tensor accompanied by its label/target? In the README of nvvl/pytorch, I find the target is set through processing, but it seemly may not work when the target is just a vector that represents video's class.

Looking forward to your reply and thanks in advance!

**Comment by jaredcasper** [comment]
Sorry for the delay, I've been a bit distracted with another project lately. :)

You are right the current code doesn't really support this.  I'm going to have to think about how to best add support for this use case.

The first way to do this that I think of is to create a queue in `VideoDataset` of the indices that are in the pipeline, so you would push into the queue in `_read_sample`, then in `_start_receive` check if the name of the tensor in the map is "label" or whatever and if so pop an index from the index queue and put the associated label/target into that tensor instead of putting it into the sequence object passed to nvvl. A bit hacky but seems like it might work.

I'll see if I can come up with a more elegant solution later and incorporate it into the code.  Ideally there would be a `get_label` function or something that can be customized and it would "just work", but that would take a bit more effort than just hacking it in as above.

In the meantime PRs are welcome. :)

**Comment by shinkyo0513** [comment]
Thank you for your response!

**Comment by Multihuntr** [comment]
I made it return a tuple of `(frames, labels)`, but that's perhaps not the correct way? Perhaps it should be `{'frames': frames, 'labels': labels}`? (Note that in this message `frames` refers to what it was returning previously [a dictionary of differently processed versions of the same sequence of frames])

(I'm pretty new to pytorch, I've not done much with it, yet, sorry if my commits are a bit messy)

**Comment by jaredcasper** [comment]
@Multihuntr added some support for labels.  Let me know if this doesn't meet your needs.
