### ISSUE TITLE
[Doubt] Does nvvl provide the feature of temporal squishing/stretching of videos?

### ISSUE THREAD

**Issue by Naman-ntc** [NVIDIA/nvvl#26]
Suppose I have a video containing 96 frames and I want data-loader to give me 16 frames but not necessarily consecutive 16 frames. As I saw from the README, (as far as I found) nvvl probably is designed for loading all possible consecutive frames.
Is there any way I can load non consecutive frames by sampling that would behave like sort of temporal augmentation?

Also just on side note, there is no rotation option provided for augmentation right??

**Comment by jaredcasper** [comment]
NVVL is designed to load consecutive frames, but it will load single frames if you ask it to. Just give it a sequence length of 1 and batch size of 16 (assuming you are using the pytorch interface) and you should get a batch of 16 random frames (there will be an extra dimension in the tensor you might want to squash for convenience).  If you want something a bit more exotic you'll have to edit or rewrite the VideoDataset/VideoLoader, but the underlying library should support it.  With the C/C++ interface its just a matter of explicitly telling it which frames you want to read.

You'll probably want to encode your videos with GOP size of 1 (to make all frames i-frames) otherwise you'll end up reading/decoding a lot of frames unnecessarily.

No rotation option is currently provided for augmentation.

**Comment by Naman-ntc** [comment]
Ohh thanks for the reply! Will check it out
