### ISSUE TITLE
VideoLoader::impl::read_file goes into an infinite loop if the packets are out of order

### ISSUE THREAD

**Issue by Multihuntr** [NVIDIA/nvvl#33]
I have a set of video files that cause the [VideoLoader::impl::read_file()](https://github.com/NVIDIA/nvvl/blob/master/src/VideoLoader.cpp#L349) function to go into an infinite loop when I try to read either of the two frames immediately before a key frame. 

Using debug mode, I've been observing how it ends up in an infinite loop.

There is a comment inside the loop that poses a question: 
```
// The following assumes that all frames between key frames
// have pts between the key frames.  Is that true?
```
The answer is: no. No it is not. I used `ffmpeg -show_packets input.mp4` to see what the packets were for my videos. It seems that they are slightly out of order from what that code assumes. In my case, the frame to which each packet belongs follows the following pattern (for each set of 3 frames, the 3rd frame comes first, then the first frame, then the second):

```
2, 0, 1, 5, 3, 4, 8, 6, 7, 11, 9, 10, 14, 12, 13, ...
```

(Where the keyframe interval is 12, and the first keyframe is frame 2 (no, I don't know why), so the next keyframe is frame 14)

So, when I request frame 12 for example: it gets told to seek to frame 12, then the frame is read with `av_read_frame` (this returns frame 14 for some reason), then it seeks back to the previous keyframe (frame 2) and then starts reading the packets sequentially. When it hits frame 14, it assumes it's gone too far again, and restarts, forever.

------------------

What can I do to fix this? Well, if I could, I'd just do a quick `ffmpeg` command to reorder the packets, but I couldn't find anything that did that. For reasons I won't get into here, it doesn't suit to completely re-encode the video file. In any case, this doesn't solve the problem in general. 

I was thinking that there might be some way to add some leeway that allows it search a few frames after the next keyframe as well. The decode order surely wouldn't be all THAT more different to the presentation order. I still think that's a bit hacky, though.

(Speaking of hacky, how does the `seek_hack` work? It's always being used as `seek_hack=2`)

Man, dealing with encoded video and libav is nasty. I'm used to python!

**Comment by jaredcasper** [comment]
Are you using x264 or hevc/x265?  When using hevc the default is to have "open gops" unless you specify the `no-open-gop=1` param when encoding.  That is the only case I've seen frames ordered outside of their gop ("gop" = group of pictures, or the frames between keyframes). I'd be interested to know if you're seeing this with x264.

It is a nasty problem when the ordering puts a frame outside of its gop (which is why for now it just assumes/requires closed gop's) and I'm not sure of the best way to handle it.  I remember considering your idea of looking past the next keyframe but can't remember now why I didn't do it.  It'd be a bit tricky because you'd have to remember the keyframe you went past and if you find the frame you are looking for, go back and start decoding at that keyframe.  But with open gops even that might not be enough since frame 12 might need info from frames before frame 14 (in your example). I'm not sure what the semantics of keyframes are with open gops.  I'll have to think/research on it some more, but have some other projects on the burner right now so no guarantees if I can get to it soon.  PRs are welcome. :)  At the very least we should be able to avoid an infinite loop and bail in this case.

The `seek_hack` thing tries to solve the problem when libavformat will, for whatever reason, seek past the frame it is asked for. It goes back 2, 4, 8, 16, ... frames before the target frame and tries again until it is telling it to seek to frame 0, in which case if it still gets a frame past the target it just gives up.  At least that is the intent.

**Comment by Multihuntr** [comment]
The videos are originally .MXF files created by a Sony PXW-FS5 camera. I'm interested in loading these in at inference time as quickly as possible. I may eventually need to put in a pull request for a sequential mode or something, but for now, I'm just trying to get them to load.

They are definitely H264 files (.MXF is the container). Trying to load them directly fails with the generic `"Can't open filename.MXF"`. So I've simply converted them to .mp4 with `ffmpeg -i filename.MXF -map v:0 -c:v copy filename.mp4` (I don't want to be re-encoding them for a single pass). Here's the line from `ffprobe` on the file.

```
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 96360 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
```

---------------------------

I've been trying to figure out why the AVSEEK_FLAG_BACKWARD doesn't seem to work as expected (which is the reason for the seek_hack, right?). It seems that each different container *can* have a different seeking function ([source code](http://ffmpeg.org/doxygen/trunk/libavformat_2utils_8c_source.html#l02528) because nothing is actually documented). I think that the `mp4` seeking function ignores the AVSEEK_FLAG_BACKWARD flag and just returns the nearest keyframe (so backwards for the first half of the group of frames, and forwards for the second half). So I re-containerised it with `.mkv` instead and that seems to consistently seek to the keyframe before (even in my case where frame 12 is decoded after frame 14, it seeked correctly to frame 2; good job, `mkv`'s `read_seek`!).

I don't know if this is a direction you want to go in, but if you assume that an `.mkv` video file is used (with it's, frankly, superior seek function :nerd_face:), then it essentially removes this problem, and also gets rid of the `seek_hack`. You will never end up accidentally going forwards, and you can just keep reading until you have all the frames (AFAIK the order in the stream is the order in which things need to be decoded, so it shouldn't be possible to have the `.mkv` seeked keyframe be after the required frames).

I've made some modifications to the loop in a [branch on my fork](https://github.com/Multihuntr/nvvl/tree/inf_loop_when_pts_is_late) that definitely won't work for non-`mkv` containers (i.e. containers that don't seek correctly), but solves the problem for me. Unsure what, if any, effects it will have on the benchmark. I'll try to run them myself and update this (but some minimalistic benchmarks I ran suggests it's about 10% faster with `mkv` and the new code).

I've only started looking into how to use the libav libraries over the past week, and I'm surprised that there are so few standards that containers adhere to.

**Comment by jaredcasper** [comment]
MKV files definitely have the best format for seeking. I don't want to limit the code to only working with MKV files though.  Sounds like using MKV and some tweaks to the reading loop got things working for you though, so that's awesome!  I'm going to close this issue for now.

**Comment by Multihuntr** [comment]
For anyone else who finds themselves running into this issue, you should convert your video to `.mkv` format to avoid this problem.

Also, I found out that the original `mxf` format that I was using DOES work with FFMPEG if you build it specifically with the mxf demuxer enabled. i.e. add `mxf` to the `--enable-demuxer=mov,matroska` line in the configuring of building FFMPEG, so that it reads `--enable-demuxer=mov,matroska,mxf`

MXF also doesn't have the seeking issue.
