### ISSUE TITLE
Question on the data obtained

### ISSUE THREAD

**Issue by msharmavikram** [NVIDIA/nvvl#34]
Reference: https://github.com/NVIDIA/nvvl/tree/master/pytorch/test

I am trying to understand the numbers that are obtained. Here are few queries - 
1. I am little surprised to note that the numerical precision has no impact on per iteration data time or in memory usage. This is kind of surprising since the data compute time and memory required should be lower for FP16. What is the reason for this to remain constant? Any thoughts?
2. What do you mean by the max of 80 in the CPU load column?

**Comment by jaredcasper** [comment]
I'm just about to head out of town for the weekend so won't be able to follow up until next week... but a couple of quick answers.

1. The decision to do fp32 or fp16 happens at the very end of the pipeline, after the image has been decoded, when the kernel to do format conversion/cropping/etc. is run.  So it doesn't make much of a difference in terms of what NVVL is doing.  It will (should) affect the actual network computation but that isn't what is being measured, we are just measuring the overhead to prepare the data to put input into the network.

2. The machine we ran the test on (a DGX-1) has 80 CPU hardware threads, so that is the maximum CPU load we could see on this system.

**Comment by jaredcasper** [comment]
I'll assume that my previous comment answered your question and close this issue.  Let me know if you have any more questions.
