### ISSUE TITLE
CUDA error 302 at line 32 in file /tmp/nvvl/src/detail/CUVideoParser.h: shared object symbol not found / CUDA error 302 at line 156 in file /tmp/nvvl/src/detail/NvDecoder.cpp: shared object symbol not found Problem decoding packet

### ISSUE THREAD

**Issue by tlikhomanenko** [NVIDIA/nvvl#9]
Hi,
I tried to create dataset and data loader 
```python
from nvvl import ProcessDesc, VideoDataset, VideoLoader
from glob import glob
filenames = glob('~/video/*.mp4')
processing = {'input': ProcessDesc(type='half', width=224, height=224)}
dataset = VideoDataset(filenames=filenames, sequence_length=5, processing=processing)                    
data_loader = VideoLoader(dataset, batch_size=8, shuffle=False)
for data in data_loader:
    print(data['input'].size())
    break
```
However, the following is printed after the dataset creation:
```
CUDA error 302 at line 32 in file /tmp/nvvl/src/detail/CUVideoParser.h: shared object symbol not found
Problem creating video parser
Problem creating video parser
```
and  the following is printed after calling the data loader iterator:
```
CUDA error 302 at line 156 in file /tmp/nvvl/src/detail/NvDecoder.cpp: shared object symbol not found
Problem decoding packet
```
Any ideas how to fix this?

Thanks!

**Comment by tlikhomanenko** [comment]
Copying the file `/usr/lib/nvidia-390/libnvcuvid.so.1` to docker container `/usr/local/cuda/lib64/stubs/` fixes the problem :). 

By the way, regenerating `libnvcuvid.so` in  `nvvl/examples/pytorch_superres/docker` with  `nvvl/examples/pytorch_superres/docker/make-stub.sh` script doesn't help me to fix the problem.

**Comment by jaredcasper** [comment]
The shared object symbol not found error comes from the loader using the stub library at runtime, which probably means it can't find the real library that should be provided by `nvidia-docker`. Are you using nvidia-docker v2?  If so, the environment variable NVIDIA_DRIVER_CAPABILITIES needs to include `video` (i.e. `NVIDIA_DRIVER_CAPABILITIES=video,compute,utility`).  This should cause `nvidia-docker` to add `/usr/lib/x86_64-linux-gnu/libnvcuvid.so.1` to the running container.  If you are using nvidia-docker v1 then `libnvcuvid.so.1` should be at `/usr/local/nvidia/lib64/libnvcuvid.so.1`.

Copying `libnvcuvid.so.1` into the image works, but is not ideal as it ties the docker image to that particular driver version.  If you try to run the image on a host with a different version of the `nvidia` kernel module installed you could run into problems.

Also, just to clarify, the `libnvcuvid.so` created by the `make-stub.sh` script is (somewhat confusingly) just a stub library to enable linking during docker image build when the real `libnvcuvid.so` isn't available (because it is added at runtime by `nvidia-docker`). It doesn't have any functionality in it and will just produce the errors mentioned above.

**Comment by jaredcasper** [comment]
ok, so this is a little wonky, and I really wish there was a cleaner way, but there isn't (that I know of). `nvidia-docker` does not provide an unversioned `.so`, so in order to build against libnvcuvid inside a running container, you need to create a symlink `libnvcuvid.so` that points to `libnvcuvid.so.1`.  The reason `nvidia-docker` doesn't provide that symlink is that docker containers are traditionally meant to run programs, not build them. The "supported" sequence is to build the library against the stub during docker build, then use the versioned `.so` provided by `nvidia-docker` at runtime.  That said, I definitely used images with the symlink put in there so I could develop inside the docker (see the end of pytorch/docker/Dockerfile.interactive).

However, the issue you are seeing with get item hanging is probably unrelated to the whole libnvcuvid mess, as a problem linking with libnvcuvid would almost certainly error out pretty quickly.  What container and codec are you using?  I've recently run into cases of hangs happening with HEVC encoded streams. If you aren't using HEVC (i.e. h264), then can you create the VideoDataset with `log_level="debug"` and post the output?
